### ISSUE TITLE
ООП Комментарии ко второй лаб. работе.

### ISSUE THREAD

**Issue by xrem** [mathslove/ITMO#1]
Для начала давай все инкапсулируем и перестанем работать с инстансами классов которые содержатся внутри магазина.

https://github.com/mathslove/ITMO/blob/7b391d2c1138598d135b985431a0abaff8d184cf/3-sem/OOP%20labs/lab2/ShopSystem/ShopManager.cs#L28

Затем все методы, которые требуются по условию лабораторной внесём в менеджер и разгрузим класс Shop, т.к. по сути это просто PoCo класс который должен хранить в себе 3 свойства.

В Main()'e нужно будет показать как ты используешь свои класс и создать минимум 3 различиных магазина, 10 типов товаров и наполнить ими магазины.

Что касается интерфейсов, они тут со сути не нужны.
https://github.com/mathslove/ITMO/blob/7b391d2c1138598d135b985431a0abaff8d184cf/3-sem/OOP%20labs/lab2/ShopSystem/Interface/IEntity.cs#L3

Если ты хотел уменьшить кол-во boilerplate кода то можно сделать Entity как абстрактный класс с shared генератором для ID'шки между всеми классами ;)

**Comment by mathslove** [comment]
@xrem, _**спасибо за отзыв!**_ Соответствующие меры были приняты, нужные люди **наказаны**, код **исправлен**. Обещаем такого больше **не повториться**.
